// ActionScript file
import mx.collections.ArrayCollection;

[Bindable]
public var quotation:ArrayCollection=new ArrayCollection([
		{No:"A01",DataType:"Contract",StartSide:"shanghai",EndSide:"beijing",Distance:1500,Forwarder:"CLLP",HarborCharges:100,TransportCharges:"1.1",CurrencyType:"CNY",Transport:"Land",VGroup:"SVW",QuotationTime:"01/01/2007",PeriodOfValidation:"12/31/2007",DeliverType:"FTL",TransportationTime:"3"},
		{No:"A02",DataType:"Contract",StartSide:"shanghai",EndSide:"zhengzhou",Distance:650,Forwarder:"CLLP",HarborCharges:100,TransportCharges:"1.2",CurrencyType:"CNY",Transport:"Land",VGroup:"SVW",QuotationTime:"01/01/2007",PeriodOfValidation:"12/31/2007",DeliverType:"FTL",TransportationTime:"1"},
		{No:"A03",DataType:"Contract",StartSide:"shanghai",EndSide:"changchun",Distance:2800,Forwarder:"CLLP",HarborCharges:100,TransportCharges:"1.2",CurrencyType:"CNY",Transport:"Land",VGroup:"SVW",QuotationTime:"01/01/2007",PeriodOfValidation:"12/31/2007",DeliverType:"FTL",TransportationTime:"5"},
		{No:"A01",DataType:"Contract",StartSide:"shanghai",EndSide:"beijing",Distance:1500,Forwarder:"CLLP",HarborCharges:100,TransportCharges:"1.4",CurrencyType:"CNY",Transport:"Land",VGroup:"SVW",QuotationTime:"01/01/2008",PeriodOfValidation:"06/30/2008",DeliverType:"FTL",TransportationTime:"3"},
		{No:"A02",DataType:"Contract",StartSide:"shanghai",EndSide:"zhengzhou",Distance:650,Forwarder:"CLLP",HarborCharges:100,TransportCharges:"1.2",CurrencyType:"CNY",Transport:"Land",VGroup:"SVW",QuotationTime:"01/01/2008",PeriodOfValidation:"06/30/2008",DeliverType:"FTL",TransportationTime:"1"},
		{No:"A03",DataType:"Contract",StartSide:"shanghai",EndSide:"changchun",Distance:2800,Forwarder:"CLLP",HarborCharges:100,TransportCharges:"1.3",CurrencyType:"CNY",Transport:"Land",VGroup:"SVW",QuotationTime:"01/01/2008",PeriodOfValidation:"06/30/2008",DeliverType:"FTL",TransportationTime:"5"},
		{No:"A01",DataType:"Contract",StartSide:"shanghai",EndSide:"beijing",Distance:1500,Forwarder:"CLLP",HarborCharges:100,TransportCharges:"1.0",CurrencyType:"CNY",Transport:"Land",VGroup:"SVW",QuotationTime:"07/01/2008",PeriodOfValidation:"12/31/2008",DeliverType:"FTL",TransportationTime:"3"},
		{No:"A02",DataType:"Contract",StartSide:"shanghai",EndSide:"zhengzhou",Distance:650,Forwarder:"CLLP",HarborCharges:100,TransportCharges:"1.1",CurrencyType:"CNY",Transport:"Land",VGroup:"SVW",QuotationTime:"07/01/2008",PeriodOfValidation:"12/31/2008",DeliverType:"FTL",TransportationTime:"1"},
		{No:"A03",DataType:"Contract",StartSide:"shanghai",EndSide:"changchun",Distance:2800,Forwarder:"CLLP",HarborCharges:100,TransportCharges:"1.0",CurrencyType:"CNY",Transport:"Land",VGroup:"SVW",QuotationTime:"07/01/2008",PeriodOfValidation:"12/31/2008",DeliverType:"FTL",TransportationTime:"5"},
		{No:"A01",DataType:"Contract",StartSide:"shanghai",EndSide:"beijing",Distance:1500,Forwarder:"CLLP",HarborCharges:100,TransportCharges:"0.8",CurrencyType:"CNY",Transport:"Land",VGroup:"SVW",QuotationTime:"01/01/2009",PeriodOfValidation:"12/31/2009",DeliverType:"FTL",TransportationTime:"3"},
		{No:"A02",DataType:"Contract",StartSide:"shanghai",EndSide:"zhengzhou",Distance:650,Forwarder:"CLLP",HarborCharges:100,TransportCharges:"0.9",CurrencyType:"CNY",Transport:"Land",VGroup:"SVW",QuotationTime:"01/01/2009",PeriodOfValidation:"12/31/2009",DeliverType:"FTL",TransportationTime:"1"},
		{No:"A03",DataType:"Contract",StartSide:"shanghai",EndSide:"changchun",Distance:2800,Forwarder:"CLLP",HarborCharges:100,TransportCharges:"0.8",CurrencyType:"CNY",Transport:"Land",VGroup:"SVW",QuotationTime:"01/01/2009",PeriodOfValidation:"12/31/2009",DeliverType:"FTL",TransportationTime:"5"},
		
		{No:"A01",DataType:"Quotation",StartSide:"shanghai",EndSide:"beijing",Distance:1500,Forwarder:"CLLP",HarborCharges:100,TransportCharges:"1.1",CurrencyType:"CNY",Transport:"Land",VGroup:"SVW",QuotationTime:"01/01/2007",PeriodOfValidation:"12/31/2007",DeliverType:"FTL",TransportationTime:"3"},
		{No:"A02",DataType:"Quotation",StartSide:"shanghai",EndSide:"zhengzhou",Distance:650,Forwarder:"CLLP",HarborCharges:100,TransportCharges:"1.2",CurrencyType:"CNY",Transport:"Land",VGroup:"SVW",QuotationTime:"01/01/2007",PeriodOfValidation:"12/31/2007",DeliverType:"FTL",TransportationTime:"1"},
		{No:"A03",DataType:"Quotation",StartSide:"shanghai",EndSide:"changchun",Distance:2800,Forwarder:"CLLP",HarborCharges:100,TransportCharges:"1.2",CurrencyType:"CNY",Transport:"Land",VGroup:"SVW",QuotationTime:"01/01/2007",PeriodOfValidation:"12/31/2007",DeliverType:"FTL",TransportationTime:"5"},
		{No:"A01",DataType:"Quotation",StartSide:"shanghai",EndSide:"beijing",Distance:1500,Forwarder:"CLLP",HarborCharges:100,TransportCharges:"1.4",CurrencyType:"CNY",Transport:"Land",VGroup:"SVW",QuotationTime:"01/01/2008",PeriodOfValidation:"06/30/2008",DeliverType:"FTL",TransportationTime:"3"},
		{No:"A02",DataType:"Quotation",StartSide:"shanghai",EndSide:"zhengzhou",Distance:650,Forwarder:"CLLP",HarborCharges:100,TransportCharges:"1.2",CurrencyType:"CNY",Transport:"Land",VGroup:"SVW",QuotationTime:"01/01/2008",PeriodOfValidation:"06/30/2008",DeliverType:"FTL",TransportationTime:"1"},
		{No:"A03",DataType:"Quotation",StartSide:"shanghai",EndSide:"changchun",Distance:2800,Forwarder:"CLLP",HarborCharges:100,TransportCharges:"1.3",CurrencyType:"CNY",Transport:"Land",VGroup:"SVW",QuotationTime:"01/01/2008",PeriodOfValidation:"06/30/2008",DeliverType:"FTL",TransportationTime:"5"},
		{No:"A01",DataType:"Quotation",StartSide:"shanghai",EndSide:"beijing",Distance:1500,Forwarder:"CLLP",HarborCharges:100,TransportCharges:"1.0",CurrencyType:"CNY",Transport:"Land",VGroup:"SVW",QuotationTime:"07/01/2008",PeriodOfValidation:"12/31/2008",DeliverType:"FTL",TransportationTime:"3"},
		{No:"A02",DataType:"Quotation",StartSide:"shanghai",EndSide:"zhengzhou",Distance:650,Forwarder:"CLLP",HarborCharges:100,TransportCharges:"1.1",CurrencyType:"CNY",Transport:"Land",VGroup:"SVW",QuotationTime:"07/01/2008",PeriodOfValidation:"12/31/2008",DeliverType:"FTL",TransportationTime:"1"},
		{No:"A03",DataType:"Quotation",StartSide:"shanghai",EndSide:"changchun",Distance:2800,Forwarder:"CLLP",HarborCharges:100,TransportCharges:"1.0",CurrencyType:"CNY",Transport:"Land",VGroup:"SVW",QuotationTime:"07/01/2008",PeriodOfValidation:"12/31/2008",DeliverType:"FTL",TransportationTime:"5"},
		{No:"A01",DataType:"Quotation",StartSide:"shanghai",EndSide:"beijing",Distance:1500,Forwarder:"CLLP",HarborCharges:100,TransportCharges:"0.8",CurrencyType:"CNY",Transport:"Land",VGroup:"SVW",QuotationTime:"01/01/2009",PeriodOfValidation:"12/31/2009",DeliverType:"FTL",TransportationTime:"3"},
		{No:"A02",DataType:"Quotation",StartSide:"shanghai",EndSide:"zhengzhou",Distance:650,Forwarder:"CLLP",HarborCharges:100,TransportCharges:"0.9",CurrencyType:"CNY",Transport:"Land",VGroup:"SVW",QuotationTime:"01/01/2009",PeriodOfValidation:"12/31/2009",DeliverType:"FTL",TransportationTime:"1"},
		{No:"A03",DataType:"Quotation",StartSide:"shanghai",EndSide:"changchun",Distance:2800,Forwarder:"CLLP",HarborCharges:100,TransportCharges:"0.8",CurrencyType:"CNY",Transport:"Land",VGroup:"SVW",QuotationTime:"01/01/2009",PeriodOfValidation:"12/31/2009",DeliverType:"FTL",TransportationTime:"5"},
		
		{No:"A01",DataType:"Quotation",StartSide:"shanghai",EndSide:"beijing",Distance:1500,Forwarder:"COSCO",HarborCharges:100,TransportCharges:"1.2",CurrencyType:"CNY",Transport:"Land",VGroup:"SVW",QuotationTime:"01/01/2007",PeriodOfValidation:"12/31/2007",DeliverType:"FTL",TransportationTime:"3"},
		{No:"A02",DataType:"Quotation",StartSide:"shanghai",EndSide:"zhengzhou",Distance:650,Forwarder:"COSCO",HarborCharges:100,TransportCharges:"1.1",CurrencyType:"CNY",Transport:"Land",VGroup:"SVW",QuotationTime:"01/01/2007",PeriodOfValidation:"12/31/2007",DeliverType:"FTL",TransportationTime:"1"},
		{No:"A03",DataType:"Quotation",StartSide:"shanghai",EndSide:"changchun",Distance:2800,Forwarder:"COSCO",HarborCharges:100,TransportCharges:"1.3",CurrencyType:"CNY",Transport:"Land",VGroup:"SVW",QuotationTime:"01/01/2007",PeriodOfValidation:"12/31/2007",DeliverType:"FTL",TransportationTime:"5"},
		{No:"A01",DataType:"Quotation",StartSide:"shanghai",EndSide:"beijing",Distance:1500,Forwarder:"COSCO",HarborCharges:100,TransportCharges:"1.1",CurrencyType:"CNY",Transport:"Land",VGroup:"SVW",QuotationTime:"01/01/2008",PeriodOfValidation:"06/30/2008",DeliverType:"FTL",TransportationTime:"3"},
		{No:"A02",DataType:"Quotation",StartSide:"shanghai",EndSide:"zhengzhou",Distance:650,Forwarder:"COSCO",HarborCharges:100,TransportCharges:"1.1",CurrencyType:"CNY",Transport:"Land",VGroup:"SVW",QuotationTime:"01/01/2008",PeriodOfValidation:"06/30/2008",DeliverType:"FTL",TransportationTime:"1"},
		{No:"A03",DataType:"Quotation",StartSide:"shanghai",EndSide:"changchun",Distance:2800,Forwarder:"COSCO",HarborCharges:100,TransportCharges:"1.1",CurrencyType:"CNY",Transport:"Land",VGroup:"SVW",QuotationTime:"01/01/2008",PeriodOfValidation:"06/30/2008",DeliverType:"FTL",TransportationTime:"5"},
		{No:"A01",DataType:"Quotation",StartSide:"shanghai",EndSide:"beijing",Distance:1500,Forwarder:"COSCO",HarborCharges:100,TransportCharges:"1.1",CurrencyType:"CNY",Transport:"Land",VGroup:"SVW",QuotationTime:"07/01/2008",PeriodOfValidation:"12/31/2008",DeliverType:"FTL",TransportationTime:"3"},
		{No:"A02",DataType:"Quotation",StartSide:"shanghai",EndSide:"zhengzhou",Distance:650,Forwarder:"COSCO",HarborCharges:100,TransportCharges:"1.1",CurrencyType:"CNY",Transport:"Land",VGroup:"SVW",QuotationTime:"07/01/2008",PeriodOfValidation:"12/31/2008",DeliverType:"FTL",TransportationTime:"1"},
		{No:"A03",DataType:"Quotation",StartSide:"shanghai",EndSide:"changchun",Distance:2800,Forwarder:"COSCO",HarborCharges:100,TransportCharges:"1.1",CurrencyType:"CNY",Transport:"Land",VGroup:"SVW",QuotationTime:"07/01/2008",PeriodOfValidation:"12/31/2008",DeliverType:"FTL",TransportationTime:"5"},
		{No:"A01",DataType:"Quotation",StartSide:"shanghai",EndSide:"beijing",Distance:1500,Forwarder:"COSCO",HarborCharges:100,TransportCharges:"1.1",CurrencyType:"CNY",Transport:"Land",VGroup:"SVW",QuotationTime:"01/01/2009",PeriodOfValidation:"12/31/2009",DeliverType:"FTL",TransportationTime:"3"},
		{No:"A02",DataType:"Quotation",StartSide:"shanghai",EndSide:"zhengzhou",Distance:650,Forwarder:"COSCO",HarborCharges:100,TransportCharges:"1.1",CurrencyType:"CNY",Transport:"Land",VGroup:"SVW",QuotationTime:"01/01/2009",PeriodOfValidation:"12/31/2009",DeliverType:"FTL",TransportationTime:"1"},
		{No:"A03",DataType:"Quotation",StartSide:"shanghai",EndSide:"changchun",Distance:2800,Forwarder:"COSCO",HarborCharges:100,TransportCharges:"1.1",CurrencyType:"CNY",Transport:"Land",VGroup:"SVW",QuotationTime:"01/01/2009",PeriodOfValidation:"12/31/2009",DeliverType:"FTL",TransportationTime:"5"},
		
		{No:"A01",DataType:"Quotation",StartSide:"shanghai",EndSide:"beijing",Distance:1500,Forwarder:"CHANGJIU",HarborCharges:100,TransportCharges:"1.2",CurrencyType:"CNY",Transport:"Land",VGroup:"SVW",QuotationTime:"01/01/2007",PeriodOfValidation:"12/31/2007",DeliverType:"FTL",TransportationTime:"3"},
		{No:"A02",DataType:"Quotation",StartSide:"shanghai",EndSide:"zhengzhou",Distance:650,Forwarder:"CHANGJIU",HarborCharges:100,TransportCharges:"1.3",CurrencyType:"CNY",Transport:"Land",VGroup:"SVW",QuotationTime:"01/01/2007",PeriodOfValidation:"12/31/2007",DeliverType:"FTL",TransportationTime:"1"},
		{No:"A03",DataType:"Quotation",StartSide:"shanghai",EndSide:"changchun",Distance:2800,Forwarder:"CHANGJIU",HarborCharges:100,TransportCharges:"1.1",CurrencyType:"CNY",Transport:"Land",VGroup:"SVW",QuotationTime:"01/01/2007",PeriodOfValidation:"12/31/2007",DeliverType:"FTL",TransportationTime:"5"},
		{No:"A01",DataType:"Quotation",StartSide:"shanghai",EndSide:"beijing",Distance:1500,Forwarder:"CHANGJIU",HarborCharges:100,TransportCharges:"1.5",CurrencyType:"CNY",Transport:"Land",VGroup:"SVW",QuotationTime:"01/01/2008",PeriodOfValidation:"06/30/2008",DeliverType:"FTL",TransportationTime:"3"},
		{No:"A02",DataType:"Quotation",StartSide:"shanghai",EndSide:"zhengzhou",Distance:650,Forwarder:"CHANGJIU",HarborCharges:100,TransportCharges:"1.2",CurrencyType:"CNY",Transport:"Land",VGroup:"SVW",QuotationTime:"01/01/2008",PeriodOfValidation:"06/30/2008",DeliverType:"FTL",TransportationTime:"1"},
		{No:"A03",DataType:"Quotation",StartSide:"shanghai",EndSide:"changchun",Distance:2800,Forwarder:"CHANGJIU",HarborCharges:100,TransportCharges:"1.4",CurrencyType:"CNY",Transport:"Land",VGroup:"SVW",QuotationTime:"01/01/2008",PeriodOfValidation:"06/30/2008",DeliverType:"FTL",TransportationTime:"5"},
		{No:"A01",DataType:"Quotation",StartSide:"shanghai",EndSide:"beijing",Distance:1500,Forwarder:"CHANGJIU",HarborCharges:100,TransportCharges:"1.2",CurrencyType:"CNY",Transport:"Land",VGroup:"SVW",QuotationTime:"07/01/2008",PeriodOfValidation:"12/31/2008",DeliverType:"FTL",TransportationTime:"3"},
		{No:"A02",DataType:"Quotation",StartSide:"shanghai",EndSide:"zhengzhou",Distance:650,Forwarder:"CHANGJIU",HarborCharges:100,TransportCharges:"1.0",CurrencyType:"CNY",Transport:"Land",VGroup:"SVW",QuotationTime:"07/01/2008",PeriodOfValidation:"12/31/2008",DeliverType:"FTL",TransportationTime:"1"},
		{No:"A03",DataType:"Quotation",StartSide:"shanghai",EndSide:"changchun",Distance:2800,Forwarder:"CHANGJIU",HarborCharges:100,TransportCharges:"1.2",CurrencyType:"CNY",Transport:"Land",VGroup:"SVW",QuotationTime:"07/01/2008",PeriodOfValidation:"12/31/2008",DeliverType:"FTL",TransportationTime:"5"},
		{No:"A01",DataType:"Quotation",StartSide:"shanghai",EndSide:"beijing",Distance:1500,Forwarder:"CHANGJIU",HarborCharges:100,TransportCharges:"1.0",CurrencyType:"CNY",Transport:"Land",VGroup:"SVW",QuotationTime:"01/01/2009",PeriodOfValidation:"12/31/2009",DeliverType:"FTL",TransportationTime:"3"},
		{No:"A02",DataType:"Quotation",StartSide:"shanghai",EndSide:"zhengzhou",Distance:650,Forwarder:"CHANGJIU",HarborCharges:100,TransportCharges:"0.8",CurrencyType:"CNY",Transport:"Land",VGroup:"SVW",QuotationTime:"01/01/2009",PeriodOfValidation:"12/31/2009",DeliverType:"FTL",TransportationTime:"1"},
		{No:"A03",DataType:"Quotation",StartSide:"shanghai",EndSide:"changchun",Distance:2800,Forwarder:"CHANGJIU",HarborCharges:100,TransportCharges:"0.9",CurrencyType:"CNY",Transport:"Land",VGroup:"SVW",QuotationTime:"01/01/2009",PeriodOfValidation:"12/31/2009",DeliverType:"FTL",TransportationTime:"5"}
		]);
		
		
		
//物流商
[Bindable]
public var forwarders:ArrayCollection=new ArrayCollection([
		{VendorName:"CLLP",Telephone:"010-12345678",Address:"chaoyang",FaxNumber:"010-12345678",Linkman:"YAOJUNJIE"},
		{VendorName:"COSCO",Telephone:"010-87654321",Address:"haidian",FaxNumber:"010-87654321",Linkman:"chengang"},
		{VendorName:"CHANGJIU",Telephone:"010-13456789",Address:"changchun",FaxNumber:"010-13456789",Linkman:"chenhongsheng"}
		]);